= ObjectTable

Render any object as a human readable table.

== Purpose

Quick visualization of data which structure is unknown.

- Showcase how to publish a component library

== Patterns used

- Embrace the cascade (CSS)
- Approval testing (snapshot)
- Design system documentation (Storybook)
- Eslint but no Prettier

=== Embrace the cascade

Even if it is not idiomatic to Svelte 5 and most Frontend frameworks, I will not use scoped style in this component library.

It means I will not use `<style>` in Svelte components.

This will allow to use CSS cascade to overwrite CSS class of the components.

A pro is I can use vanilla css style without the need of any preprocessor.

Example in link:src/lib/ObjectTable.svelte[]

[source,html]
----
include::src/lib/ObjectTable.svelte[tag=global-style-in-svelte-component]
----

Style can be then implemented is a plain css file.

link:static/style.css[]

[source,css]
----
include::static/style.css[tag=classic-css-style]
----

And imported in the link:src/app.html[]

[source,html]
----
include::src/app.html[tag=css-classic-stylesheet]
----


